# Generated by Django 6.0.6 on 2026-06-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_bio_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='login_otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='login_otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
